# Generated by Django 3.2.6 on 2021-08-22 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address_1', models.CharField(default='', max_length=30)),
                ('address_2', models.CharField(default='', max_length=30)),
                ('address_3', models.CharField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=30)),
                ('state', models.CharField(default='', max_length=2)),
                ('zip_code', models.CharField(default='', max_length=12)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('fax_number', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=30)),
                ('facility', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Facility_Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=30)),
                ('bed_number', models.CharField(max_length=30)),
                ('unit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.units')),
            ],
        ),
    ]
