# Generated by Django 3.2.6 on 2021-08-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='facility',
            order_with_respect_to='name',
        ),
        migrations.AlterOrderWithRespectTo(
            name='units',
            order_with_respect_to='facility',
        ),
    ]
