# Generated by Django 3.2.6 on 2021-08-24 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20210822_1157'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff_Member_With_Assignments',
            new_name='Staff_Member_With_Assignments_By_Room',
        ),
        migrations.RemoveField(
            model_name='staff_member_with_assignments_by_room',
            name='unit',
        ),
        migrations.AddField(
            model_name='staff_member_with_assignments_by_room',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.facility_rooms'),
        ),
        migrations.CreateModel(
            name='Staff_Member_With_Assignments_By_Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.roles')),
                ('staff_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.units')),
            ],
        ),
    ]
