# Generated by Django 3.2.6 on 2021-08-26 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210824_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_member',
            name='credential',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='this_credential', to='user.credentials'),
        ),
    ]
