# Generated by Django 3.2.6 on 2021-09-05 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20210822_1157'),
        ('user', '0003_alter_staff_member_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Member_Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.roles')),
                ('staff_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ManyToManyField(to='organization.Units')),
            ],
        ),
    ]
